#!/bin/sh

. bootrr

TEST_CASE_ID="$1"
NUM_CPUS="$2"

if [ -z "${TEST_CASE_ID}" -o -z "${NUM_CPUS}" ]; then
	echo "Usage: $0 <test-case-id> <#cpus>"
	exit 1
fi

CPU=0

while [  $CPU -le $NUM_CPUS ]; do
	[ -f /sys/devices/system/cpu/cpu${CPU}/cpufreq/scaling_driver ] || test_report_exit fail
	CPU=$(expr ${CPU} + 1)
done
test_report_exit pass
