#!/bin/sh

TEST_CASE_ID="$1"
PARTITION="$2"

if [ -z "${TEST_CASE_ID}" -o -z "${PARTITION}" ]; then
	echo "Usage: $0 <test-case-id> <partition>"
	exit 1
fi

if [ -L /dev/disk/by-partlabel/${PARTITION} ]; then
	TEST_RESULT="pass"
else
	TEST_RESULT="fail"
fi

echo "${TEST_CASE_ID}: ${TEST_RESULT}"
