#!/bin/sh

TEST_CASE_ID="$1"
DRIVER="$2"
DEVICE="$3"

if [ -z "${TEST_CASE_ID}" -o -z "${DRIVER}" -o -z "${DEVICE}" ]; then
	echo "Usage: $0 <test-case-id> <driver> <device>"
	exit 1
fi

if [ -L /sys/bus/*/drivers/${DRIVER}/${DEVICE} ]; then
	TEST_RESULT="pass"
else
	TEST_RESULT="fail"
fi

lava-test-case "${TEST_CASE_ID}" --result ${TEST_RESULT}
