#!/bin/sh

. bootrr

TEST_CASE_ID="$1"
PARTITION=/dev/disk/by-partlabel/userdata

timeout 10 [ -L ${PARTITION} ] || test_report_exit blocked

if [ -d /lib/firmware -o -L /lib/firmware ]; then
	test_report_exit skip
fi

mkdir -p /mnt
mount -t ext4 ${PARTITION} /mnt || test_report_exit failed

ln -s /mnt/lib/firmware /lib/firmware

test_report_exit pass
