#!/bin/sh

. bootrr

TEST_CASE_ID="$1"
LOC="$2"
LOW="$3"
HIGH="$4"

if [ -z "${TEST_CASE_ID}" -o -z "${LOC}" -o -z "${LOW}" -o -z "${HIGH}" ]; then
	echo "Usage: $0 <test-case-id> <path> <low> <high> [<timeout>]"
	exit 1
fi

[ -r "${LOC}" ] || test_report_exit fail

val=$(cat "${LOC}")
if [ "${val}" -ge "${LOW}" -a "${val}" -le "${HIGH}" ]; then
	test_report_exit pass
else
	test_report_exit fail
fi
