#!/bin/sh

# APCS
assert_driver_present apcs-ipc-driver-present qcom_apcs_ipc
assert_device_present apcs-ipc-device-probed qcom_apcs_ipc 17990000.*

# GCC
assert_driver_present gcc-driver-present gcc-sdm845
assert_device_present gcc-device-probed gcc-sdm845 100000.*

# I2C GENI
assert_driver_present i2c-geni-driver-present geni_i2c
assert_device_present i2c-geni-geni1-i2c3-probed geni_i2c a88000.*

# QFPROM
assert_driver_present qfprom-driver-present qcom,qfprom
assert_device_present qfprom-device-probed qcom,qfprom 780000.*

# SCM
assert_driver_present scm-driver-present qcom_scm
assert_device_present scm-device-probed qcom_scm firmware:scm

# Serial
assert_driver_present geni-uart-driver-present qcom_geni_serial
assert_device_present geni-uart-geni1-uart2-probed qcom_geni_serial a84000.*

# SMEM
assert_driver_present smem-driver-present qcom-smem
assert_device_present smem-device-probed qcom-smem smem

# SMMU

# TCSR mutex
assert_driver_present tcsr-mutex-driver-present qcom_hwspinlock
assert_device_present tcsr-mutex-device-probed qcom_hwspinlock hwlock

# Timer

# TLMM
assert_driver_present tlmm-driver-present sdm845-pinctrl
assert_device_present tlmm-device-probed sdm845-pinctrl 3400000.*

# APR
assert_driver_present apr-bus-driver-present qcom,apr

# GLINK/SMEM

# GLINK/SPSS

# IPCROUTER

# SMP2P
assert_driver_present smp2p-driver-present qcom_smp2p
assert_device_present smp2p-adsp-device-probed qcom_smp2p *adsp*
assert_device_present smp2p-modem-device-probed qcom_smp2p *modem*
assert_device_present smp2p-slpi-device-probed qcom_smp2p *cdsp*
assert_device_present smp2p-slpi-device-probed qcom_smp2p *dsps*

# SPCOM

# CCI

# CPP

# CSID

# CSIPHY

# Face Detect

# JPEG

# VFE

# FastRPC

# QCrypto

# PRNG
assert_driver_present msm-rng-driver-present msm_rng
assert_device_present msm-rng-device-probed msm_rng 793000.*

# Coresight

# Watchdog
assert_driver_present qcom-wdt-driver-present qcom-wdt
assert_device_present qcom-wdt-device-probed qcom-wdt 17980000.*

# PCIe

# QMP phy

# PMIC
## Charger

## clkdiv

## Coincell

## Fuel guage

## GPIO

## Haptics

## LABIBB

## LPG

## PON

## QNovo

## Regulators

## RTC

# SPMI
assert_driver_present spmi-pmic-arb-driver-present spmi_pmic_arb
assert_device_present spmi-pmic-arb-device-probed spmi_pmic_arb c440000.*

## temp-alarm

## VADC

## WLED

# CPUfreq

# MPM

# SPM

# Tsens
assert_driver_present tsens-driver-present qcom-tsens
assert_device_present tsens0-device-probed qcom-tsens c263000.*
assert_device_present tsens1-device-probed qcom-tsens c265000.*

# ADSP PIL

# Modem PIL

# rmtfs memory

# Secure PIL

# Sensor PIL

# UFS QMP
assert_driver_present ufs-phy-driver-present qcom-qmp-phy
assert_device_present ufs-phy-probed qcom-qmp-phy 1d87000.*

# SDHCI

# UFSHCD
assert_driver_present ufs-hcd-driver-present ufshcd-qcom
assert_device_present ufs-hcd-device-probed ufshcd-qcom 1d84000.*
