#!/bin/sh

# APCS
assert_driver_present apcs-ipc-driver-present qcom_apcs_ipc

# GCC
assert_driver_present gcc-driver-present gcc-msm8998
assert_device_present gcc-device-probed gcc-msm8998 100000.*

# Serial
assert_driver_present msm_serial-driver-present msm_serial
assert_device_present msm_serial-uart8-probed msm_serial c1b0000.*

# SPMI PMIC arb
assert_driver_present spmi-pmic-arb-driver-present spmi_pmic_arb
assert_device_present spmi-pmic-arb-device-probed spmi_pmic_arb 800f000*

#echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
