#!/bin/sh

#RPMH
assert_driver_present cmd-db-driver-present cmd-db
assert_driver_present rpmh-driver-present rpmh
assert_driver_present rpmh-clock-driver-present clk-rpmh
assert_driver_present rpmh-regulator-driver-present qcom-rpmh-regulator
assert_driver_present rpmh-pd-driver-present qcom-rpmhpd

assert_device_present cmd-db-device-probed cmd-db 80860000.*
assert_device_present rpmh-device-probed rpmh 18200000.*
assert_device_present rpmh-clock-device-probed clk-rpmh 18200000.*
assert_device_present rpmh-pm8009-regulator-device-probed qcom-rpmh-regulator *pm8009*
assert_device_present rpmh-pm8150-regulator-device-probed qcom-rpmh-regulator *pm8150-*
assert_device_present rpmh-pm8150l-regulator-device-probed qcom-rpmh-regulator *pm8150l-*

# GCC
assert_driver_present gcc-driver-present gcc-sm8250
assert_device_present gcc-device-probed gcc-sm8250 100000.*

# SCM
assert_driver_present scm-driver-present qcom_scm
assert_device_present scm-device-probed qcom_scm firmware:scm

# Serial
assert_driver_present geni-uart-driver-present qcom_geni_serial
assert_device_present geni-uart-uart9-probed qcom_geni_serial a90000.*

# SMEM
assert_driver_present smem-driver-present qcom-smem
assert_device_present smem-device-probed qcom-smem smem
assert_driver_present smem-socinfo-driver-present qcom-socinfo

# TCSR mutex
assert_driver_present tcsr-mutex-driver-present qcom_hwspinlock
assert_device_present tcsr-mutex-device-probed qcom_hwspinlock hwlock

# TLMM
assert_driver_present tlmm-driver-present sm8250-pinctrl
assert_device_present tlmm-device-probed sm8250-pinctrl f100000.*

# SMP2P
assert_driver_present smp2p-driver-present qcom_smp2p
assert_device_present smp2p-slpi-device-probed qcom_smp2p *cdsp*
assert_device_present smp2p-adsp-device-probed qcom_smp2p *lpass*
assert_device_present smp2p-slpi-device-probed qcom_smp2p *slpi*

# SPMI
assert_driver_present spmi-pmic-arb-driver-present spmi_pmic_arb
assert_device_present spmi-pmic-arb-device-probed spmi_pmic_arb c440000.*

# UFS QMP
assert_driver_present ufs-phy-driver-present qcom-qmp-phy
assert_device_present ufs-phy-probed qcom-qmp-phy 1d87000.*

# UFSHCD
assert_driver_present ufs-hcd-driver-present ufshcd-qcom
assert_device_present ufs-hcd-device-probed ufshcd-qcom 1d84000.*
