#!/bin/sh

#RPMH
assert_driver_present cmd-db-driver-present cmd-db
assert_driver_present rpmh-driver-present rpmh
assert_driver_present rpmh-clock-driver-present clk-rpmh
assert_driver_present rpmh-regulator-driver-present qcom-rpmh-regulator
assert_driver_present rpmh-pd-driver-present qcom-rpmhpd

assert_device_present cmd-db-device-probed cmd-db 85fe0000.*
assert_device_present rpmh-device-probed rpmh 179c0000.*
assert_device_present rpmh-clock-device-probed clk-rpmh 179c0000.*
assert_device_present rpmh-pm8998-regulator-device-probed qcom-rpmh-regulator *pm8998*
assert_device_present rpmh-pmi8998-regulator-device-probed qcom-rpmh-regulator *pmi8998*

# AOSS
assert_driver_present aoss-reset-driver-present qcom_aoss_reset
assert_driver_present aoss-qmp-driver-present qcom_aoss_qmp

assert_device_present aoss-reset-device-probed qcom_aoss_reset c2a0000.*
assert_device_present aoss-qmp-device-probed qcom_aoss_qmp c300000.*

# PDC
assert_driver_present pdc-reset-driver-present qcom_pdc_reset
assert_device_present pdc-reset-device-probed qcom_pdc_reset b2e0000.*

# APCS
assert_driver_present apcs-ipc-driver-present qcom_apcs_ipc
assert_device_present apcs-ipc-device-probed qcom_apcs_ipc 17990000.*

# GCC
assert_driver_present gcc-driver-present gcc-sdm845
assert_device_present gcc-device-probed gcc-sdm845 100000.*

# GENI
assert_driver_present geni-se-driver-present geni_se_qup
assert_device_present geni-wrapper0-device-probed geni_se_qup 8c0000.*
assert_device_present geni-wrapper1-device-probed geni_se_qup ac0000.*

# I2C GENI
assert_driver_present i2c-geni-driver-present geni_i2c
assert_device_present i2c-geni-i2c10-probed geni_i2c a88000.*
assert_device_present i2c-geni-i2c11-probed geni_i2c a8c000.*
assert_device_present i2c-geni-i2c14-probed geni_i2c a98000.*

# QFPROM
assert_driver_present qfprom-driver-present qcom,qfprom
assert_device_present qfprom-device-probed qcom,qfprom 784000.*

# SCM
assert_driver_present scm-driver-present qcom_scm
assert_device_present scm-device-probed qcom_scm firmware:scm

# Serial
assert_driver_present geni-uart-driver-present qcom_geni_serial
#assert_device_present geni-uart-uart3-probed qcom_geni_serial 88c000.*
assert_device_present geni-uart-uart6-probed qcom_geni_serial 898000.*
assert_device_present geni-uart-uart9-probed qcom_geni_serial a84000.*

# SMEM
assert_driver_present smem-driver-present qcom-smem
assert_device_present smem-device-probed qcom-smem smem
assert_driver_present smem-socinfo-driver-present qcom-socinfo

# SMMU
assert_driver_present arm-smmu-driver-present arm-smmu
assert_device_present apps-smmu-device-probed arm-smmu 15000000.*
assert_device_present adreno-smmu-device-probed arm-smmu 5040000.*

# SPI
assert_driver_present spi-geni-driver-present geni_spi
assert_device_present spi-geni-spi2-probed geni_spi 888000.*

# TCSR mutex
assert_driver_present tcsr-mutex-driver-present qcom_hwspinlock
assert_device_present tcsr-mutex-device-probed qcom_hwspinlock hwlock

# Timer

# TLMM
assert_driver_present tlmm-driver-present sdm845-pinctrl
assert_device_present tlmm-device-probed sdm845-pinctrl 3400000.*

# GLINK/SMEM

# GLINK/SPSS

# IPCROUTER

# SMP2P
assert_driver_present smp2p-driver-present qcom_smp2p
assert_device_present smp2p-slpi-device-probed qcom_smp2p *cdsp*
assert_device_present smp2p-adsp-device-probed qcom_smp2p *lpass*
assert_device_present smp2p-modem-device-probed qcom_smp2p *mpss*
assert_device_present smp2p-slpi-device-probed qcom_smp2p *slpi*

# SPCOM

# CCI

# CPP

# CSID

# CSIPHY

# Face Detect

# JPEG

# VFE

# FastRPC

# QCrypto

# PRNG
assert_driver_present qcom-rng-driver-present qcom_rng
assert_device_present qcom-rng-device-probed qcom_rng 793000.*

# Coresight

# Watchdog
assert_driver_present qcom-wdt-driver-present qcom_wdt
assert_device_present qcom-wdt-device-probed qcom_wdt 17980000.*

# PCIe
assert_driver_present qcom-pcie-driver-present qcom-pcie
assert_device_present qcom-pcie-gen2-device-probed qcom-pcie 1c00000.*
#assert_device_present qcom-pcie-gen3-device-probed qcom-pcie 1c08000.*

# QMP phy
assert_driver_present qcom-qmp-driver-present qcom-qmp-phy
assert_device_present qcom-qmp-pcie-probed qcom-qmp-phy 1c06000.*
#assert_device_present qcom-qhp-pcie-probed qcom-qmp-phy 1c0a000.*

# PMIC
## Charger

## clkdiv

## Coincell

## Fuel guage

## GPIO

## Haptics

## LABIBB

## LPG

## PON

## QNovo

## Regulators

## RTC

# SPMI
assert_driver_present spmi-pmic-arb-driver-present spmi_pmic_arb
assert_device_present spmi-pmic-arb-device-probed spmi_pmic_arb c440000.*

## temp-alarm

## VADC

## WLED

# CPUfreq
assert_driver_present osm-driver-present qcom-cpufreq-hw
assert_device_present osm-device-probed qcom-cpufreq-hw 17d43000.*
assert_cpufreq_enabled cpufreq-cpu-enabled 7

#CPUidle
assert_cpuidle_enabled cpuidle-cpu-enabled 7

# MPM

# SPM

# Tsens
assert_driver_present thermal-driver-tsens-present qcom-tsens
assert_device_present thermal-device-tsens0-probed qcom-tsens c263000.*
assert_device_present thermal-device-tsens1-probed qcom-tsens c265000.*
# 8 thermal zones: cpu x 8
STATE=""
RANGE=""
for num in `seq 0 7`
do
    STATE="$STATE /sys/class/thermal/thermal_zone"${num}"/mode"
    RANGE="$RANGE /sys/class/thermal/thermal_zone"${num}"/temp"
done

state_check thermal-zone-enabled enabled "$STATE"
value_in_range thermal-zone-temperature 25000 60000 "$RANGE"

# PAS driver
assert_driver_present qcom-pas-remoteproc-driver-present qcom_q6v5_pas
assert_device_present remoteproc-adsp-device-probed qcom_q6v5_pas *adsp*
assert_device_present remoteproc-cdsp-device-probed qcom_q6v5_pas *cdsp*

# Modem PIL
assert_driver_present qcom-mss-remoteproc-driver-present qcom-q6v5-mss
assert_device_present qcom-mss-remoteproc-device-probed qcom-q6v5-mss 4080000.*

# rmtfs memory
assert_driver_present rmtfs-mem-driver-present qcom_rmtfs_mem
assert_device_present rmtfs-mem-device-probed qcom_rmtfs_mem 88f00000.*

# Secure PIL

# Sensor PIL

# UFS QMP
assert_driver_present ufs-phy-driver-present qcom-qmp-phy
assert_device_present ufs-phy-probed qcom-qmp-phy 1d87000.*

# SDHCI
assert_driver_present sdhci-msm-driver-present sdhci_msm
assert_device_present sdhc_2-device-probed sdhci_msm 8804000.*

# UFSHCD
assert_driver_present ufs-hcd-driver-present ufshcd-qcom
assert_device_present ufs-hcd-device-probed ufshcd-qcom 1d84000.*
